name: Publish to NPM
on:
  push:
    branches:
      - main
      - master
jobs:
  test:
    uses: ./.github/workflows/test.yml
  publish:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test
      
      - name: Build
        run: npm run build

      - name: Fix README for NPM
        run: sed -i '/logo-dark\.svg/d' README.md

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
